const toast=document.getElementById('toast');let toastTimer;
function notify(message){toast.textContent=message;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.hidden=true,3000)}
document.querySelectorAll('[data-hex]').forEach(button=>button.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(button.dataset.hex);notify(`${button.dataset.hex} copied`)}catch{notify(`Color: ${button.dataset.hex}`)}}));
for(const [id,message] of [['primary-demo','Continue selected. Primary actions move the current step forward.'],['secondary-demo','Options selected. Secondary actions offer a choice.'],['quiet-demo','You can continue with what you know and return to this detail later.']])document.getElementById(id).addEventListener('click',()=>document.getElementById('action-feedback').textContent=message);
document.getElementById('budget').addEventListener('input',event=>{const input=event.target;const invalid=input.value===''||!input.validity.valid;input.setAttribute('aria-invalid',String(invalid));const help=document.getElementById('budget-help');help.textContent=invalid?'Enter a whole dollar amount of $0 or more.':`USD · $${input.value} spending limit. This is a demo.`;help.classList.toggle('cs-error',invalid)});
document.getElementById('stay').addEventListener('change',event=>{document.getElementById('stay-feedback').textContent=event.target.value==='I’m not sure yet'?'The flow should help identify a suitable destination before scheduling delivery.':'Only ask for details needed to arrange support.'});
const days={today:{time:'TODAY, 6–7 PM',title:'Three prepared meals',owner:'Demo Kitchen · Owner: Jordan, demo coordinator',status:'confirmed',label:'✓ Confirmed',cost:'$12',icon:'meal'},tomorrow:{time:'TOMORROW, 9–10 AM',title:'A ride to your appointment',owner:'Demo Ride · Awaiting driver acceptance',status:'requested',label:'◷ Requested',cost:'$8',icon:'ride'},day3:{time:'DAY 3, 10 AM',title:'Check in on what’s next',owner:'Fictional caregiver Alex · Reminder only',status:'',label:'Planned',cost:'$0',icon:'people'}};
document.querySelectorAll('[data-day]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-day]').forEach(x=>x.setAttribute('aria-pressed',String(x===button)));const d=days[button.dataset.day];document.getElementById('day-content').innerHTML=`<article class="service-card"><div class="service-icon"><svg class="cs-icon" aria-hidden="true"><use href="assets/icons.svg#${d.icon}"/></svg></div><div><span class="eyebrow">${d.time}</span><h4>${d.title}</h4><p>${d.owner}</p><span class="cs-badge ${d.status?'cs-badge--'+d.status:''}">${d.label}</span></div><strong>${d.cost}<small>Your share</small></strong></article>`}));
document.getElementById('payment-demo').addEventListener('click',()=>{document.getElementById('payment-feedback').textContent='Mock approval recorded: $20 from family + $74 from demo sponsor. No money moved. Ride acceptance is still pending.';notify('Mock approval recorded — no charge')});
